on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

      - name: Check out source code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}

  call-ci:
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/ci.yaml

  attach-artifacts:
    needs: [ release-please, call-ci ]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ needs.call-ci.outputs.openmenu-artifact-id }},${{ needs.call-ci.outputs.tools-artifact-id }}
          path: ./artifacts

      - name: Upload release artifacts
        run: |
          zip -r -j ./artifacts/openmenu.zip ./artifacts/openmenu/
          zip -r -j ./artifacts/tools-linux-x64.zip ./artifacts/tools/
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            ./artifacts/openmenu.zip \
            ./artifacts/tools-linux-x64.zip \
            --clobber
